### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by femtotrader** [Weswit/Lightstreamer-example-StockList-client-python#2]
Hello,

it will be nice if you could add Python 3 support
(same code for Python 2 and Python 3)

Kind regards

**Comment by femtotrader** [comment]
I try to solve this using this PR but it doesn't seems to work.

Any idea ?

**Comment by femtotrader** [comment]
`compat.py` is inspired from `pandas.compat` and `pandas.io.common.py`

https://github.com/pydata/pandas/blob/master/pandas/compat/__init__.py
https://github.com/pydata/pandas/blob/master/pandas/io/common.py

**Comment by femtotrader** [comment]
with `six` https://pypi.python.org/pypi/six

```
from six import iteritems
from six.moves.urllib.request import urlopen
from six.moves.urllib.parse import urlparse, urljoin, urlencode
```

I'm using Anaconda Python with Python 3 being my default Python install

I can switch to Python 2 using

```
$ source activate py2
```

(inspired from http://continuum.io/blog/anaconda-python-3 )

**Comment by gfinocchiaro** [comment]
It works well in Python 2 if you update compat.py as follows:
from
```from urllib2 import urlopen as _urlopen```
to:
```from urllib import urlopen as _urlopen```.

Anyway, with Python3, the problem is how http response is managed, since the urlopen method returns an HTTPResponse object, which does not have any "readline"() method.
You can use "read", but remember that Lightstreamer works with http streaming, so you cannot read the whole response. You should split the response, looking for "\r\n" in order to parse command response...

**Comment by femtotrader** [comment]
Thanks for fixing this.

**Comment by femtotrader** [comment]
Hello,

it will be very nice if you could have a look at
https://github.com/ig-python/ig-markets-stream-api-python-library

It works fine fine Python 2.
I add a compat.py (like in your project) but with Python 3 I only get

```
$ python sample.py
New state: connecting Lightstreamer session
New state: disconnected from Lightstreamer
```

Any idea ?
