### ISSUE TITLE
unsubscribe all subscriptions

### ISSUE THREAD

**Issue by femtotrader** [Weswit/Lightstreamer-example-StockList-client-python#7]
Hello,

it may be useful (to avoid to do it on the user/dev side to be able to unsubscribe all subscriptions (before disconnecting)

```
def unsubscribe(self, subcription_key=None):
    """Unregister the Subscription associated to the
    specified subscription_key.
    if no subcription_key is given it unsubscribe all.
    """
    if subcription_key is None:
        subscriptions = self._subscriptions.copy() # To avoid a RuntimeError: dictionary changed size during iteration
        for subcription_key in subscriptions:
            self._unsubscribe(subcription_key)
    else:
        self._unsubscribe(subcription_key)
```

So instead of keeping `sub_key` and do

```
lightstreamer_client.unsubscribe(sub_key)
```

we will be able to do

```
lightstreamer_client.unsubscribe()
```

Kind regards

**Comment by gfinocchiaro** [comment]
Hi,

such feature would not be compliant with the actual Lightstreamer Unified Client API model.
Please have a look [here](http://www.lightstreamer.com/docs/client_javascript_uni_api/LightstreamerClient.html#unsubscribe)
Anyway, in the near future we will take in consideration your proposal in order to extend the API model. Thanks a lot for your suggestion!

**Comment by femtotrader** [comment]
Hi,

So that's probably better to call it `unsubscribe_all` ?

**Comment by gfinocchiaro** [comment]
Hi,

the problem is not related to name of the method, but to the feature itself, which is not provided by the current Unified API.

**Comment by femtotrader** [comment]
Ok understood
